Repository ansible/ansible-content-actions, pull requests merged in 2025-09, with the labels that each got.

#74 chore: adopt renovate
  .github/dependabot.yml
  .github/workflows/ack.yml
  .github/workflows/cml_lab_create.yaml
  .github/workflows/cml_lab_destroy.yaml
  .github/workflows/cml_network_integration.yaml
  .pre-commit-config.yaml
  renovate.json
Labels: chore

#75 chore: correct release drafter config
  .github/release-drafter.yml
Labels: chore

#78 fix the AH release job
  .github/workflows/release_ah.yaml
Labels: fix

#79 chore: enable scheduled runs
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
Labels: chore, ignore-for-release
